### ISSUE TITLE
Doesn't seem to work on TFS 2017 Update 1

### ISSUE THREAD

**Issue by jsingla** [konste/TfsPermissionVisualizer#2]
TFS 2017 Update 1
Tested with VS2015 and VS2017

Steps:
1. Tried generating graph from 'Tools' > 'Generate Graph Dependency of TFS Group Membership'
2. In the 'Connect to Team Foundation Server' dialog, selected the collection and the team project and clicked 'Connect'

Actual result:
Appears to do some processing but in the end displays a blank output (screenshot below)
![screen shot 2017-07-03 at 3 33 57 pm](https://user-images.githubusercontent.com/1568002/27797316-1c34a52a-6005-11e7-85e1-155c1dc1a0b3.png)

**Comment by konste** [comment]
My team finally switched from TFS to VSTS, so I don't have TFS anymore to try it... and I feel good about it, sorry. Unless it is a matter of life and death you have to debug it yourself.

**Comment by jsingla** [comment]
Thanks for getting back. It's not absolutely critical, just means we can't use the extension.

**Comment by alondero** [comment]
@konste is there something like this available within VSTS?

**Comment by konste** [comment]
Nothing I'm aware of. On the other hand VSTS security model seems substantially simpler so may be it does not need such extension?
