### ISSUE TITLE
Permission denied when trying to run this.

### ISSUE THREAD

**Issue by jamesoneill** [konste/TfsPermissionVisualizer#3]
Hi, I have inherited a visualstudio.com team services.  I am now the owner have all permissions but i get an error when trying to access any of the team service i am  a member of. access denied.

**Comment by konste** [comment]
This VS add-in specifically targets TFS and is not supposed to work with VSTS - very different permissions model.

**Comment by jamesoneill** [comment]
Thank you for the swift reply, concise and to the point.
